
1 - Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.


In [53]:
#Tek boyutlu arraylere vektor, cok boyutlu arraylere ise matris denir.


2 - 10 elemanli bir listeden NumPy Array’i olusturunuz.


In [3]:
import numpy as np

list=[1,2,3,4,5,6,7,8,9,99]
a=np.array(list)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 99])


3 - Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.


In [4]:
np.zeros((10,10), dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)


4 - Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.


In [5]:
np.ones((10,10), dtype = 'float32')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)


5 - Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.


In [6]:
np.full((10,10),9,dtype = 'int32')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=int32)


6 - 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.


In [7]:
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])


7 - (-1) ile 1 arasinda 30 adet Array olusturunuz.


In [8]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])


8 - 0 ile 30 arasinda 5x6’lik bir matris olusturun.


In [9]:
np.random.randint(0,30,(5,6))

array([[ 8,  1, 23, 15, 11, 24],
       [ 9, 25, 13, 20,  9,  2],
       [29, 11, 26, 10,  1, 29],
       [15, 21, 19, 20, 12, 20],
       [19, 21,  2, 22, 13, 14]])


9 - Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.


In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


10 - 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; 
a) eleman sayisini 
b) boyut bilgisini/sayisini 
c) satir X sutun bilgisini 
d) veri tipini numpy metodlariyla yazdiriniz. 


In [11]:
a=np.random.randint(0,10,(5,10),dtype = 'int32')
a.size # eleman sayisi

50

In [12]:
a.ndim # boyut bilgisi

2

In [13]:
a.shape # satir sutun bilgisi

(5, 10)

In [14]:
a.dtype #veri tipi

dtype('int32')


11 - 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)


In [15]:
np.random.randint(10, size = (3,4,7))

array([[[6, 2, 4, 4, 5, 2, 1],
        [9, 1, 6, 0, 1, 2, 7],
        [1, 8, 1, 5, 0, 7, 8],
        [6, 5, 2, 4, 9, 8, 4]],

       [[4, 7, 0, 1, 9, 0, 3],
        [6, 0, 9, 3, 5, 4, 8],
        [3, 7, 1, 5, 1, 6, 9],
        [3, 2, 4, 7, 3, 8, 5]],

       [[7, 7, 0, 8, 4, 0, 3],
        [0, 4, 0, 2, 5, 0, 3],
        [5, 5, 9, 5, 7, 9, 0],
        [3, 8, 9, 6, 0, 3, 3]]])


12 - Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)


In [16]:
a = np.arange(10)
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])


13 - 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.


In [17]:
a=np.arange(5)
b=np.arange(6)
c=np.arange(7)
d=np.arange(8)

np.concatenate([a,b,c,d])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 7])


14 - 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.


In [18]:
a=np.arange(3,5)
b=np.random.randint(10,20,(2,2))

np.vstack([a,b])

array([[ 3,  4],
       [13, 15],
       [11, 17]])


15 - Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?


In [19]:
# axis = 0 ;satir bazli birlestirme ,  axis = 1 ; sutun bazli birlestirme icin kullanilir.


16 - Farkli boyutlardaki arraylari satir ve sutun bazli ayri ayri birlestiriniz.


In [20]:
a = np.random.randint(0,10,(2,3))
b = np.random.randint(5,15,(2,4))
np.hstack([a,b]) # satir bazli birlesme


array([[ 2,  2,  3,  9,  7, 10, 13],
       [ 5,  0,  8, 10,  9,  7,  6]])

In [21]:
c = np.random.randint(0,6,(3,2))
d = np.random.randint(10,18,(4,2))
np.vstack([c,d]) # sutun bazli birlsme

array([[ 5,  4],
       [ 2,  0],
       [ 2,  5],
       [10, 11],
       [17, 16],
       [11, 13],
       [13, 11]])


17 - 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.


In [22]:
list = [i for i in range(0,11)] # 10 elemanli liste 

np.split(list,[2,4,6]) # 4 farkli array

[array([0, 1]), array([2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10])]


18 - Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.


In [23]:
a = np.random.randint(0,10, 5)

b = np.sort(a)
b[::-1]


array([9, 9, 8, 6, 4])


19 - 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin


In [24]:
a = np.random.randint(0,50, 20)
print(a)
b=[3,5,7]
a[b]

[10 43 43 16 33  4 26 35 30 23 19 20  7 42 23 23 35 41 31 35]


array([16,  4, 35])


20 - 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz


In [25]:
a = np.random.randint(0,50, 10)
print(a)
a[4] = 345
a

[ 1  4 31 38 10 49 13 29  4 13]


array([  1,   4,  31,  38, 345,  49,  13,  29,   4,  13])


21 - “Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.


In [26]:
# Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise diagonal matris denir.
# Trace matrix ise bu asal kosegen ustundeki elemanlarin toplamidir.



22 - 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)


In [27]:
a = np.random.randint(20, size = (5, 5))
a[0,0], a[1,1], a[2,2], a[3,3], a[4,4]

(13, 13, 11, 4, 2)


23 - 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.


In [28]:
a = np.arange(10, 20)
a[3:]

array([13, 14, 15, 16, 17, 18, 19])


24 - 10X10 luk bir matris olusturunuz ve ;

a. 3.satir ve 5.sutuna ulasiniz.
b. 5.sutunun tum satirlarina ulasiniz.
c. Tum sutunlarin 2.satirlarina ulasiniz.
d. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
e. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
f. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
g. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
h. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz


In [29]:
a = np.random.randint(0, 100, (10, 10))
a


array([[64, 40, 54, 82, 51, 47, 46, 89, 16, 22],
       [ 1, 76, 59, 20, 18, 89, 93, 88, 13, 34],
       [28, 70, 95, 47, 41, 42, 19, 56, 69, 67],
       [87, 69, 95, 32,  2, 11, 46, 84, 48, 75],
       [ 7, 43, 48, 83, 60,  0, 31, 44, 67, 75],
       [46, 33, 56, 95, 87, 57, 18, 39, 68, 99],
       [68, 82, 27,  8, 93, 55, 13, 33, 61, 34],
       [41, 62, 30, 76, 88, 61, 84,  1, 10, 70],
       [98, 84, 80, 79, 89, 72, 57, 24, 91, 49],
       [55, 14, 67, 59, 35, 68, 67, 57, 74, 55]])

In [30]:
a[3,5] # 3.satir ve 5. satir

11

In [31]:
a[:, 5] # 5. sutunun tum satirlari

array([47, 89, 42, 11,  0, 57, 55, 61, 72, 68])

In [32]:
a[2, :] # tum sutunlarin 2. satirlari

array([28, 70, 95, 47, 41, 42, 19, 56, 69, 67])

In [33]:
a[2:7,:] # tum sutunlarin 2. ve 7. satirlari

array([[28, 70, 95, 47, 41, 42, 19, 56, 69, 67],
       [87, 69, 95, 32,  2, 11, 46, 84, 48, 75],
       [ 7, 43, 48, 83, 60,  0, 31, 44, 67, 75],
       [46, 33, 56, 95, 87, 57, 18, 39, 68, 99],
       [68, 82, 27,  8, 93, 55, 13, 33, 61, 34]])

In [34]:
a[2:5, 3:7] #  satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerler

array([[47, 41, 42, 19],
       [32,  2, 11, 46],
       [83, 60,  0, 31]])

In [35]:
a[5:,:4] # satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerler

array([[46, 33, 56, 95],
       [68, 82, 27,  8],
       [41, 62, 30, 76],
       [98, 84, 80, 79],
       [55, 14, 67, 59]])

In [36]:
[a[:,3],a[:,6],a[:,9]] # sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlari

[array([82, 20, 47, 32, 83, 95,  8, 76, 79, 59]),
 array([46, 93, 19, 46, 31, 18, 13, 84, 57, 67]),
 array([22, 34, 67, 75, 75, 99, 34, 70, 49, 55])]

In [37]:
a[5,5] = 1990  # 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz
a

array([[  64,   40,   54,   82,   51,   47,   46,   89,   16,   22],
       [   1,   76,   59,   20,   18,   89,   93,   88,   13,   34],
       [  28,   70,   95,   47,   41,   42,   19,   56,   69,   67],
       [  87,   69,   95,   32,    2,   11,   46,   84,   48,   75],
       [   7,   43,   48,   83,   60,    0,   31,   44,   67,   75],
       [  46,   33,   56,   95,   87, 1990,   18,   39,   68,   99],
       [  68,   82,   27,    8,   93,   55,   13,   33,   61,   34],
       [  41,   62,   30,   76,   88,   61,   84,    1,   10,   70],
       [  98,   84,   80,   79,   89,   72,   57,   24,   91,   49],
       [  55,   14,   67,   59,   35,   68,   67,   57,   74,   55]])


25 - 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) 
ve numpy metodlariyla asagidaki islemleri uygulayin; 
20 den buyuk olan kac deger var. 
a)30’dan kucuk kac deger var 
b)icerisinde 33 gecen kac deger var 
c)olusturulan arrayin tum elemanlarini 5 ile carpin. 
d)olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.


In [38]:
a = np.arange(0, 50, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [39]:
np.sum(a>20)

5

In [40]:
np.sum(a<30)

6

In [41]:
np.sum(a==33)

0

In [42]:
np.multiply(5, a)

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [43]:
np.array(a%2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])


26 - 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; 
ortalamasini aliniz. 
a)standart sapmasini aliniz. 
b)varyansini aliniz. 
c)median’ini aliniz. 
d)en kucuk degeri bulunuz. 
e)en buyuk degeri bulunuz.


In [44]:
a = np.random.random((1,50))
a

array([[0.40339702, 0.43678562, 0.04520246, 0.90312952, 0.59242816,
        0.10836167, 0.16684335, 0.50643891, 0.89125775, 0.09283066,
        0.40469876, 0.26473185, 0.42610589, 0.51273908, 0.1579103 ,
        0.19403802, 0.43868031, 0.33456239, 0.34483193, 0.32614728,
        0.74734559, 0.07905146, 0.18310745, 0.96698162, 0.46581394,
        0.99765554, 0.83547007, 0.82561623, 0.71750622, 0.74638725,
        0.56473305, 0.56871688, 0.79062411, 0.79305346, 0.75694939,
        0.27792604, 0.71111789, 0.84645335, 0.30674152, 0.45735517,
        0.66043421, 0.18900413, 0.35591205, 0.67420689, 0.63280746,
        0.69159583, 0.60398689, 0.69040763, 0.07713596, 0.3133531 ]])

In [45]:
np.mean(a)

0.5015714264689136

In [46]:
np.std(a)

0.26305096074063006

In [47]:
np.var(a)

0.0691958079465685

In [48]:
np.median(a)

0.48612642224301694

In [49]:
np.min(a)

0.04520245707024495

In [50]:
np.max(a)

0.997655542308239


Master odev ; 

Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz. Matris uretme islemini np.random.random((axb)) fonksiyonu ile yapabilirsiniz.(size kalmis) 1:30 Cuma aksamina kadar odevlerin hepsini gondermenizi rica ediyorum. Ayrica, matris odevinin ekran goruntusunu yada ekran videosunu gruba atmanizi istiyorum. Deneme matrislerini de gonderebilirsiniz. 


In [52]:
import timeit
start = timeit.default_timer()
sayac=0
while True:       
    c=np.random.random((10,10))-np.random.random((10,10))
    sayac+=1
    for i in range(10):
        if c[i,i]>0.1 or c[i,i]<-0.1:
            break        
    else:
        break
stop=timeit.default_timer()
print(f'''matris:
{c}
sayaç: {sayac}
süre: {stop-start}''')
    

matris:
[[-0.02687814  0.22111375 -0.49354153  0.44553595  0.71855582  0.26651047
   0.23892762  0.15736045 -0.14626429 -0.61323181]
 [ 0.35932732  0.05667116  0.87620361  0.56924978 -0.51766271 -0.22417466
  -0.05787473  0.21014492  0.46347503 -0.48143225]
 [ 0.27184942  0.70660313  0.05660265  0.85919581  0.34019085 -0.21848016
  -0.15634817  0.06261458  0.09624684  0.04136388]
 [-0.27659295  0.34058224 -0.11021442  0.09837319 -0.45630196 -0.45420038
   0.33580941 -0.58663046 -0.85523011  0.14422653]
 [-0.52029601  0.3630969  -0.56093542  0.04515617 -0.09630533 -0.27877778
   0.43718031  0.19254152  0.73610033  0.06934661]
 [ 0.08192653  0.50637279  0.08489422  0.46164443 -0.71179143  0.09314766
  -0.38106095  0.16595501  0.40647964  0.82885157]
 [ 0.56438049 -0.04708814  0.24349741 -0.16394224 -0.15482673 -0.74936399
  -0.04842171  0.10224784  0.37756426 -0.55222342]
 [-0.08837395 -0.01230783 -0.05914083  0.27698988 -0.56164935 -0.08901556
  -0.09727004  0.06012295  0.68067852 -0.01